server: 
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  ##################### DB #####################
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/account_b?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 950110xn
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: GATHERING-SERVICE
logging:
  level:
    com:
      codingapi:
        txlcn:DEBUG
mybatis:
  mapper-locations : classpath:mapper.xml

ribbon:
  MaxAutoRetriesNextServer: 0
  #开启feign的熔断功能
feign:
  hystrix:
    enabled: true



